source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EquatableArray_Example', :exclusive => true do
  pod "EquatableArray", :path => "../"
end

target 'EquatableArray_Tests', :exclusive => true do
  pod "EquatableArray", :path => "../"

  
end
